import "./globals.css";
import type { Metadata } from "next";
// importing the Clerk provider
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // wrapping the app in the Clerk provider
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header/>
          <main className="container">
            <div className="flex item-start justify-center min-h-screen">
              <div className="mt-20">{children}</div>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
